name: Lighthouse CI
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  # Triggers the workflow when pull request is opened or updated
  workflow_run:
    workflows: ["Pull Request Workflow"]
    types:
      - opened
      - synchronize

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Build
        uses: actions/jekyll-build-pages@v1
  lighthouseci:
    runs-on: ubuntu-latest
    needs: build # Ensure this action executed after build
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 20
      - run: npm install -g @lhci/cli@0.11.x
      - run: lhci collect --staticDistDir=_site
      - name: Archive lighthouse results
        uses: actions/upload-artifact@v3
        with:
          name: lighthouse-report
          path: .lighthouseci
