name: Lighthouse CI
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  # Triggers the workflow when pull request is opened or updated
  pull_request:
    # types: [opened, synchronize]

jobs:
  lighthouseci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        uses: actions/jekyll-build-pages@v1
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm install -g @lhci/cli@0.11.x
      - run: lhci collect --staticDistDir=${{ github.workspace }}/_site
      - name: Archive lighthouse results
        uses: actions/upload-artifact@v4
        with:
          name: lighthouse-report
          path: .lighthouseci
