name: Lighthouse CI
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  # Triggers the workflow when pull request is opened or updated
  pull_request:
    # types: [opened, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        uses: actions/jekyll-build-pages@v1
  # lighthouseci:
    # runs-on: ubuntu-latest
    # needs: build # Ensure this action executed after build
    # steps:
      - name: Display Workspace Path
        # env:
        #   SECRETS_VARS: ${{ github.workspace }}
        # run: echo "$SECRETS_VARS" > "secrets.txt"
        run: echo "Worksace Path ${{ github.workspace }}"
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm install -g @lhci/cli@0.11.x
      - run: lhci collect --staticDistDir=${{ github.workspace }}/_site
      - name: Archive lighthouse results
        uses: actions/upload-artifact@v4
        with:
          name: lighthouse-report
          path: .lighthouseci
