name: Lighthouse CI
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  # Triggers the workflow when pull request is opened or updated
  pull_request:

jobs:
  lighthouseci:
    runs-on: ubuntu-latest
    steps:
      # Build
      #ref: https://github.com/actions/starter-workflows/tree/main/pages
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Ruby
        uses: ruby/setup-ruby@8575951200e472d5f2d95c625da0c7bec8217c42 # v1.161.0
        with:
          ruby-version: '3.1' # Not needed with a .ruby-version file
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
          cache-version: 0 # Increment this number if you need to re-download cached gems
      # Fix gemfile not found issue
      - name: Bundle init
        run: bundle init && bundle add jekyll
      - name: Build with Jekyll
        # Outputs to the './_site' directory by default
        run: bundle exec jekyll build --baseurl ./
        env:
          JEKYLL_ENV: production
      - name: Archive build results
        uses: actions/upload-artifact@v4
        with:
          name: site
          path: _site

      # Lighthiuse CI
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm install -g @lhci/cli@0.11.x
      # Collect Lighthouse results from jekyll-build-pages default destination
      - run: lhci collect --staticDistDir=_site
      - name: Archive lighthouse results
        uses: actions/upload-artifact@v4
        with:
          name: lighthouse-report
          path: .lighthouseci
